spring:
  datasource:
    url: jdbc:mysql://localhost:3306/StudentProgressAnalysis?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: spa
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8082
  servlet:
    session:
      timeout: 86400
      cookie:
        name: sessionid
        path: /

mybatis:
  mapper-locations: classpath:com/spa/dao/*.xml
  type-aliases-package: com.spa.model